Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
Lint/Eval:
  Enabled: false
ClassLength:
  Enabled: false
MutableConstant:
  Enabled: false
ClassVars:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'data/*'
    - 'lib/sapphire_bot/config.rb'
    - 'Gemfile'
